# Site
name: "hsnberg.com"
title: "heisenberg"
description: "Chemistry, Music, Life"
logo: 'assets/images/wa-hsnberg.png'
favicon: 'assets/images/wa-hsnberg.png'
#baseurl: /mediumish-theme-jekyll
google_analytics: 'G-R49M9VD5LR'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
destination: docs

# Authors
authors:
  shiv:
    name: Shiv
    display_name: Shiv Mehrotra
    avatar: 'assets/images/shiv-avatar.png'
 #   gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: shiv.mehrotra.me@gmail.com
    web: /about.html
    #twitter: https://twitter.com/wowthemesnet
    description: "Lead content editor hsnberg.com"
  hsnberg:
    name: Heisenberg
    display_name: Heisenberg    
    #avatar: 'assets/images/avatar.png'
  #  gravatar: b1cc14991db7a456fcd761680bbc8f81
  #  email: wowthemesnet@gmail.com
  #  web: https://www.wowthemes.net
  #  twitter: https://twitter.com/wowthemesnet
    description: "Say my name."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
